version: 2

project_name: cfl

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cfl
    main: ./cmd/cfl
    binary: cfl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/open-cli-collective/confluence-cli/internal/version.Version={{.Version}}
      - -X github.com/open-cli-collective/confluence-cli/internal/version.Commit={{.Commit}}
      - -X github.com/open-cli-collective/confluence-cli/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# Homebrew cask with auto-quarantine removal for unsigned binaries
homebrew_casks:
  - name: cfl
    repository:
      owner: open-cli-collective
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/open-cli-collective/confluence-cli
    description: "Command-line interface for Atlassian Confluence"
    binary: cfl
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cfl"]
    caveats: |
      cfl has been installed. Run 'cfl init' to configure.

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^Merge pull request'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Other'
      order: 999
