version: 2

project_name: cfl

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cfl
    main: ./cmd/cfl
    binary: cfl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/rianjs/confluence-cli/internal/version.Version={{.Version}}
      - -X github.com/rianjs/confluence-cli/internal/version.Commit={{.Commit}}
      - -X github.com/rianjs/confluence-cli/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

brews:
  - name: cfl
    repository:
      owner: rianjs
      name: homebrew-confluence-cli
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/rianjs/confluence-cli
    description: "Command-line interface for Atlassian Confluence"
    license: MIT
    install: |
      bin.install "cfl"
    test: |
      system "#{bin}/cfl", "--version"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^Merge pull request'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Other'
      order: 999
